name: absensi_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  camera: ^0.10.5+9
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  intl: ^0.19.0
  lottie: ^3.0.0
  google_mlkit_face_detection: ^0.5.0
  cloud_firestore: ^4.15.5
  firebase_core: ^2.25.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/raw/